import { SpectrumCard } from '../../../types';

export const GENERAL_THEME: { name: string; image: string; cards: SpectrumCard[] } = {
  name: 'General',
  image: '/static/themes/general.png',
  cards: [
  { left: "Overrated", right: "Underrated" },
  { left: "Highbrow", right: "Lowbrow" },
  { left: "Timeless", right: "Trendy" },
  { left: "Risky", right: "Safe" },
  { left: "Serious", right: "Silly" },
  { left: "Guilty Pleasure", right: "Respectable" },
  { left: "Mainstream", right: "Niche" },
  { left: "Lazy", right: "Effortful" },
  { left: "Intimidating", right: "Approachable" },
  { left: "Underrated Skill", right: "Overrated Skill" },

  { left: "Relaxing", right: "Stressful" },
  { left: "Old Person Thing", right: "Young Person Thing" },
  { left: "Looks Better Than It Is", right: "Is Better Than It Looks" },
  { left: "Bad First Impression", right: "Good First Impression" },
  { left: "More Art", right: "More Science" },
  { left: "Ethical", right: "Unethical" },
  { left: "Waste of Time", right: "Good Use of Time" },
  { left: "Low Commitment", right: "High Commitment" },
  { left: "Unnecessary", right: "Essential" },
  { left: "Hard to Learn", right: "Easy to Learn" },

  { left: "Feels Longer Than It Is", right: "Feels Shorter Than It Is" },
  { left: "Cheap", right: "Expensive" },
  { left: "Annoying", right: "Endearing" },
  { left: "Obsolete", right: "Future-Proof" },
  { left: "More Fun to Watch", right: "More Fun to Do" },
  { left: "High Status", right: "Low Status" },
  { left: "Pretentious", right: "Down-to-Earth" },
  { left: "More Style", right: "More Substance" },
  { left: "Overcomplicated", right: "Elegant" },
  { left: "Forgettable", right: "Memorable" },

  { left: "Bad Idea", right: "Good Idea" },
  { left: "Hard to Quit", right: "Easy to Quit" },
  { left: "Embarrassing", right: "Impressive" },
  { left: "Unreliable", right: "Reliable" },
  { left: "Background Noise", right: "Center of Attention" },
  { left: "Short-Term Reward", right: "Long-Term Reward" },
  { left: "Unhealthy", right: "Healthy" },
  { left: "More Luck", right: "More Skill" },
  { left: "Passive", right: "Active" },
  { left: "Uninspiring", right: "Inspiring" },

  { left: "Bad for Society", right: "Good for Society" },
  { left: "Too Much Effort", right: "Worth the Effort" },
  { left: "Outdated", right: "Ahead of Its Time" },
  { left: "More Work", right: "More Play" },
  { left: "Introvert Thing", right: "Extrovert Thing" },
  { left: "Stress-Inducing", right: "Calming" },
  { left: "Forgettable Trend", right: "Lasting Change" },
  { left: "More Chaos", right: "More Order" },
  { left: "Hard to Explain", right: "Easy to Explain" },
  { left: "Bad Investment", right: "Good Investment" },

  { left: "Unromantic", right: "Romantic" },
  { left: "Pointless", right: "Meaningful" },
  { left: "Low Stakes", right: "High Stakes" },
  { left: "Inconvenient", right: "Convenient" },
  { left: "Overstimulating", right: "Understimulating" },
  { left: "Hard to Trust", right: "Easy to Trust" },
  { left: "More Form", right: "More Function" },
  { left: "Misunderstood", right: "Well Understood" },
  { left: "Feels Fake", right: "Feels Genuine" },
  { left: "Forget the Past", right: "Honor Tradition" }
  ]
};